version: "3.5"

services:
  postgres:

    image: postgres
    container_name: postgres

    volumes:
      - /data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres

    networks:
      - backend

    restart: always
    
  nginx:

    build: nginx/
    container_name: nginx

    depends_on:
      - postgres
    
    networks:
      - backend

    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  
    restart: always
  
  haproxy:

    build: haproxy/
    container_name: haproxy

    volumes:
      - F:/testproject/haproxy/haproxycfg/haproxy.cfg:/etc/haproxy/haproxy.cfg
      - F:/testproject/haproxy/cert:/etc/ssl/certs
    ports:
      - "8443:443"

    depends_on:
      - postgres
      - nginx

    networks:
      - backend
      - frontend

    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

    restart: always

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge

